version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes: 
    deploy:
      - ./nginx.conf:/etc/nginx/nginx.conf
      replicas: 2 
      resources: 
        limits: 
          cpus: '0.5'
          memory: 512M

  php:
    image: php:latest
    volumes:
      ./php:/var/www/html
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
